error: Add MissingToolError
This exception type is meant for situations where a specific tool is
missing on a certain host that would be required to perform some action.

Signed-off-by: Rahix <rahix@rahix.de>