error: Add CommandFailure exception type
This exception type is used whenever an `exec0()` method detects a
command returning non-zero exit code.

Adapt bash & ash shell implementations to use the new type and fix
selftests which rely on the old way to report such failures.

Signed-off-by: Harald Seiler <hws@denx.de>