error: Add MachineNotFoundError
When a role is requested which does not exist, raise a custom exception
type to indicate this.

Signed-off-by: Harald Seiler <hws@denx.de>