error: Introduce ApiViolationError vs MachineError
With tbot, we can see two kinds of exceptions throughout the code-base:

- "ApiViolationError"s where the calling code just did something that is
  illegal by tbot's API contract.  For example using a path for a wrong
  host in a command or requesting an exclusively owned instance from a
  context.  These kind of exceptions indicate that downstream code has
  to be fixed - there is clear blame for the test-writer here.

- "MachineError"s on the other hand indicate that the remote systems tbot was
  interacting with behaved unexpectedly.  For example, a kernel panic
  was detected or a command timed out.  These kind of exceptions
  (usually) indicate that the software we are testing has problems,
  while the test-code is fine.  Of course this may also be caused by
  buggy test-code but in contrast to the "ApiViolationError" this isn't
  a clear-cut case.

It makes sense to distinguish between the two because
"ApiViolationError" in most cases shouldn't be handled by test-code.
Instead it should be bubbled up all the way to the programmer so they
can fix their code.

Thus, add two base-classes from which the respective exceptions should
inherit in the future.

Signed-off-by: Harald Seiler <hws@denx.de>