error: Inherit from ApiViolationError
Use the new `ApiViolationError` as the base-class for the 3 exception
types `AbstractMethodError`, `WrongHostError`, and `ContextError`.  They
all mark situations where test-code is wrong so this base-class is most
appropriate.

Signed-off-by: Harald Seiler <hws@denx.de>